import React from 'react';
import Header from 'components/Header';
import List from 'components/List/List';

const listItems = [
  { title: 'Expand me', content: 'Thank you' },
  { title: 'Click me', content: 'Saved me' },
  { title: 'Tap me', content: 'Hey, watch it!' },
  { title: 'Open me', content: 'I am free' }
];

export default () => (
  <article className="home">
    <Header title="About" className="header-blue" />
    <List items={listItems} collapsible />
  </article>
);

export const someSillyDataToMakeThisLookHeavy = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pretium elit id ex interdum, sagittis tristique libero semper. Proin molestie dictum magna id varius. Maecenas imperdiet odio diam, quis sagittis risus congue vel. Curabitur sit amet dapibus neque. Nulla metus augue, finibus non convallis id, posuere et dui. Duis gravida justo leo, vel tincidunt ex lobortis luctus. Mauris at porttitor lectus. Vestibulum vel sapien luctus, vestibulum neque maximus, gravida velit
Sed consequat ex eu metus dignissim mattis. Phasellus vel imperdiet nibh. Phasellus vitae facilisis odio. Etiam sit amet dui nec tortor interdum rutrum. Donec nibh lorem, consequat ac convallis sed, vestibulum id enim. Mauris quis luctus metus. Quisque elementum imperdiet risus eget pulvinar. Suspendisse erat tortor, tincidunt a sollicitudin et, eleifend eget quam. Nullam porta, velit ut iaculis convallis, enim leo pellentesque nibh, vitae dictum lorem nulla eu mauris. Vivamus tincidunt, ante id hendrerit tincidunt, magna nisl dictum nibh, eget aliquam urna lacus in metus. Nunc scelerisque lectus dolor, eget ornare dui convallis vitae. Vestibulum scelerisque, ligula a tristique consequat, dui dui pretium ex, malesuada lobortis lectus justo ac lacus
Pellentesque at lorem enim. Morbi sed magna pharetra magna mattis venenatis mattis at lorem. Sed sem orci, varius at lacus non, rutrum accumsan tortor. Quisque condimentum nec diam in feugiat. Sed lobortis, dui quis molestie bibendum, nunc est cursus massa, non varius purus odio ut risus. Etiam cursus eros mauris, sed porta felis maximus eu. Praesent sagittis a felis quis maximus. In cursus, eros non venenatis commodo, quam purus feugiat justo, ornare vehicula massa justo eget risus
Nam sollicitudin ac dui sed fringilla. Ut lacus purus, ullamcorper a malesuada et, egestas eu elit. Etiam quis ipsum ut quam placerat cursus. Suspendisse interdum lorem eu ornare dapibus. Vivamus vulputate ante id porttitor faucibus. Sed nec bibendum libero. Nullam iaculis ut turpis non placerat. Mauris semper, sem quis pulvinar aliquet, libero sapien elementum magna, porta interdum neque libero quis ipsum. Donec elementum facilisis nisl, quis convallis tellus rutrum et
Aenean molestie metus eget nisl cursus convallis. Nulla facilisis, nibh a maximus elementum, nulla enim blandit sapien, non mollis sapien dui eget nisl. Ut porta sem eu augue cursus aliquet. Donec ut felis a tortor semper hendrerit quis non massa. Ut pellentesque sed sapien venenatis gravida. Nam quis ligula at felis varius placerat ut id ipsum. Nulla sed malesuada arcu, at hendrerit sapien. Nullam a quam et velit congue vestibulum sed et tellus. In erat enim, scelerisque id pellentesque in, pretium elementum est. Quisque et sodales mi. Nulla facilisi. Fusce vitae lacus sollicitudin, cursus mauris eu, luctus turpis. Sed ac dapibus tortor, eu consectetur mauris. Donec placerat urna ut lacinia ultricies
Curabitur feugiat nulla dapibus odio suscipit porta. Aliquam in lectus at tortor vestibulum iaculis mollis aliquet ipsum. Nullam ac consectetur ante. Aliquam est nisl, porttitor sit amet metus a, ullamcorper maximus elit. Nam commodo ornare odio, non elementum felis imperdiet elementum. Pellentesque sed vestibulum magna. Pellentesque a leo enim. Aenean scelerisque purus vel fermentum ornare. Cras sollicitudin orci quis ex elementum, quis dapibus nulla sagittis. Nam quis est nec justo vulputate aliquet. Fusce ipsum tellus, aliquet egestas dignissim non, volutpat quis dui. Proin quis turpis eget purus tempus tincidunt mollis sit amet velit. Curabitur gravida a nibh in rutrum. In lorem diam, cursus eget odio sodales, porttitor dapibus risus. Nullam pharetra semper dui, at viverra tortor pulvinar sed
Quisque eros ipsum, condimentum eget malesuada vel, pellentesque vel sapien. Quisque sollicitudin nisi non sapien malesuada, ullamcorper venenatis turpis rutrum. Vestibulum ut magna pretium, consequat nunc eget, lobortis enim. In volutpat ipsum a ultricies tristique. Aliquam ut mi vestibulum, scelerisque augue sit amet, sodales eros. Donec pretium odio et augue rhoncus, quis maximus nunc tincidunt. Integer faucibus nec ex vitae consectetur. Suspendisse in euismod eros. Mauris accumsan vitae purus sit amet sagittis. Vestibulum massa ipsum, varius vitae luctus id, laoreet a lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed eu augue a enim efficitur volutpat. Aenean varius, urna a iaculis pellentesque, velit urna condimentum turpis, pulvinar aliquam est ligula ac nunc
Curabitur rutrum auctor sagittis. Pellentesque at dictum ante. Morbi bibendum libero id dignissim semper. Integer bibendum erat ac commodo laoreet. Integer aliquam elit ipsum, nec egestas nibh auctor a. Nulla in ligula nunc. In auctor eros fermentum, pharetra neque sit amet, dictum ipsum. Duis aliquam justo vel tristique suscipit. Sed semper ante ut pellentesque porttitor
Fusce eleifend leo at ligula lacinia maximus id sit amet neque. Phasellus velit sapien, suscipit quis malesuada sodales, porta non dui. Mauris bibendum aliquam faucibus. Proin lobortis tortor a fringilla interdum. Etiam et nisl et enim elementum luctus. Donec dictum elit enim, in laoreet ipsum aliquam sed. Nullam pellentesque tempor nunc ut accumsan. Proin vitae risus posuere, pretium eros vitae, laoreet metus. Nulla facilisi. Vestibulum non pharetra lorem
Cras viverra rutrum feugiat. Nullam in iaculis elit. Praesent at lectus vel mi mollis condimentum. Maecenas accumsan tincidunt dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dignissim accumsan varius. Proin ullamcorper dapibus placerat. Nullam sodales neque tellus, sit amet placerat dui interdum eget. Vivamus ligula felis, suscipit vitae leo at, pretium feugiat turpis. Vestibulum et cursus nisi. Nullam vitae finibus ipsum. Curabitur rutrum pharetra nunc ac lobortis. Cras non lacinia metus
Nam porta imperdiet commodo. Proin non lectus mauris. Nulla varius in turpis id maximus. Vestibulum aliquet accumsan vulputate. Suspendisse volutpat enim in magna vestibulum, eget malesuada lorem egestas. Nunc aliquam nunc velit, eu fermentum ligula posuere condimentum. Proin non sagittis quam. Sed imperdiet suscipit ligula eget convallis. Nullam volutpat ante nibh, at auctor nunc tincidunt et. Sed id mattis odio
Aliquam aliquet urna lectus, et aliquet neque mollis gravida. Ut aliquam imperdiet ex nec ultricies. Aliquam tempor convallis augue sed pellentesque. Sed maximus massa lobortis bibendum placerat. Morbi lacus quam, vehicula a pharetra vel, sagittis sit amet lacus. Etiam quam metus, ultricies malesuada efficitur vitae, molestie sed ipsum. Nulla pretium, risus vitae rutrum tincidunt, ante lacus blandit massa, sed placerat elit tellus sit amet elit. Integer gravida, lectus a varius pulvinar, arcu orci luctus purus, in lobortis lacus metus id leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc egestas rhoncus gravida. Sed eget auctor tortor. Mauris eget posuere leo. Nullam volutpat elit sagittis ante mollis imperdiet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas imperdiet efficitur nulla, ac scelerisque nisi
Aliquam cursus, ligula sit amet laoreet mollis, mauris nibh ultrices justo, vitae feugiat neque orci et orci. Cras tellus ligula, fermentum ut mollis non, malesuada lobortis sapien. Vivamus mattis dapibus nisl, eget ornare ligula sodales ut. Vestibulum vitae neque eu neque pharetra tincidunt vitae id eros. Etiam cursus interdum felis ut malesuada. Sed euismod quam vel viverra malesuada. Sed mattis magna ligula, ut iaculis odio tempor in. Sed imperdiet enim vel dictum rhoncus. Aliquam sed ligula erat
Maecenas pulvinar imperdiet lectus, vel pulvinar ex. Nulla consectetur tortor at rhoncus pretium. Nam imperdiet lectus ut interdum luctus. Sed convallis ullamcorper libero sit amet lobortis. Curabitur egestas magna et felis mattis aliquam. Curabitur et dapibus urna, ut malesuada quam. Donec porttitor ornare nibh a sagittis. Vestibulum facilisis erat id tellus elementum porta. In sit amet tristique libero
Vestibulum at nisl libero. Sed tincidunt convallis dui, sed efficitur augue aliquet vitae. Quisque gravida ante sit amet ante imperdiet, vel feugiat erat vestibulum. Nulla facilisi. Sed est augue, cursus a lacinia sed, egestas sit amet ligula. Ut lorem lacus, ornare non feugiat at, feugiat sed quam. Nullam consequat, turpis id finibus efficitur, velit turpis ornare felis, sit amet condimentum risus nibh at urna. Etiam fringilla porta turpis, id tempor quam posuere at. Maecenas ultricies, ipsum ac viverra gravida, sapien eros dignissim sem, eget porta lectus nibh non nunc. Integer ullamcorper massa magna, vitae varius nunc sollicitudin sed. Nulla pulvinar suscipit tortor, ac luctus quam gravida eu. Nulla mattis massa vitae mi rutrum, cursus elementum nunc luctus. Duis metus nulla, egestas nec rhoncus sollicitudin, pharetra ac enim. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ac tempus felis. Integer in sapien sem
Sed eleifend volutpat erat, nec fringilla metus porta elementum. Phasellus mattis lobortis ipsum id ullamcorper. Nullam vitae sapien viverra, volutpat magna at, ornare nibh. Morbi vel ornare dolor. Maecenas condimentum sed sem et porttitor. Quisque placerat ut justo a condimentum. Donec tellus tortor, malesuada finibus neque ac, semper commodo turpis. Aliquam sollicitudin sem sit amet nisl feugiat rhoncus. Duis odio sem, gravida aliquam lorem ut, lacinia ornare felis. Donec eleifend nunc nibh, non vestibulum massa maximus ut. Nunc id tellus id ante fermentum dictum. Cras condimentum urna eu augue efficitur, quis laoreet ex pulvinar. Nullam vulputate nec ex dapibus vulputate
Aenean a dui quis nibh interdum porttitor. Etiam laoreet orci enim, sit amet venenatis justo scelerisque non. Maecenas id erat id nulla congue vehicula. Etiam varius tellus ut bibendum tincidunt. Duis sit amet diam ultrices, rutrum orci ac, posuere mauris. Aenean placerat at lorem in hendrerit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse tempus sem a efficitur tincidunt. Mauris iaculis mollis dictum. Morbi pharetra consectetur ex sit amet semper. Nullam suscipit tellus placerat odio laoreet, a luctus ipsum gravida. Cras maximus augue ut nibh egestas dignissim. In vel nisl venenatis, convallis ex ac, imperdiet erat. Integer commodo, ex et ornare mattis, est velit porttitor felis, eu maximus orci est vel enim. Nam metus mi, suscipit et ultrices sed, pharetra sit amet tortor
Sed quis feugiat arcu, non mattis est. Integer non dictum nibh. Sed porttitor dolor arcu, vitae faucibus purus lobortis eu. Quisque at nisi ultricies, dapibus nisi eu, pharetra risus. Morbi eu mi mi. Mauris gravida sit amet sem eu fermentum. Duis consectetur dolor risus, et volutpat felis sollicitudin ac
Maecenas eget justo tellus. Proin eu lacus dictum, consectetur ex eu, commodo orci. Quisque porttitor finibus eleifend. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse mattis ut neque a placerat. Donec suscipit ultricies nunc sed pulvinar. Mauris eget risus sit amet elit finibus dictum ut a augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin eget mi eget libero imperdiet pretium a at ex
Morbi aliquam dictum felis, a iaculis erat. Aliquam ultrices blandit lorem, sit amet aliquam magna mattis sed. Nulla nec aliquam risus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse condimentum justo eget massa viverra, ut pulvinar leo cursus. Morbi vehicula, turpis id volutpat placerat, magna velit lacinia ante, nec faucibus tellus massa sit amet mauris. Donec luctus ligula in tristique viverra. Proin et vestibulum orci
Donec vitae convallis odio. Donec sem eros, pellentesque vel suscipit sit amet, elementum quis nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam pretium tortor ut ipsum consequat scelerisque in vel magna. Vestibulum auctor imperdiet ligula sed condimentum. Fusce cursus ultrices ultrices. Vivamus lectus leo, molestie vitae neque ac, posuere mattis mi. Vestibulum tempus odio mauris, sit amet fringilla erat euismod eget. Sed eu odio quis lacus efficitur porttitor at vitae velit. Pellentesque tristique pretium magna ac vestibulum
Vivamus pulvinar pellentesque dui, et blandit purus hendrerit at. Donec bibendum efficitur felis, ac hendrerit leo molestie nec. Vestibulum eu mauris vitae dui bibendum tempor. Curabitur condimentum suscipit lorem in egestas. Praesent molestie sed neque sed congue. Phasellus auctor augue in eros mattis, at tempor ante congue. Proin tempor non metus a pellentesque. Fusce ultrices, nisi eget pellentesque cursus, ex ante elementum orci, tempor egestas nisi erat et dui
Nullam euismod tortor tempor est lacinia, vel ullamcorper velit mollis. Integer commodo nisl sit amet tellus malesuada, in finibus leo fermentum. Pellentesque ultrices ultrices finibus. Cras auctor suscipit neque, a pharetra augue laoreet sed. Cras tincidunt tristique nulla id luctus. Morbi in augue dignissim, sagittis mauris ut, vestibulum neque. Proin suscipit porta ligula, at suscipit ipsum gravida sed. Proin blandit felis a elit sollicitudin, sit amet fringilla nunc auctor. Mauris at lectus tristique, feugiat lorem ac, viverra diam. Donec aliquet nisi quis fermentum blandit. Maecenas eu metus eu risus condimentum sollicitudin. Maecenas eros nibh, laoreet sed nibh at, tempus rhoncus eros. Aliquam molestie urna sapien, nec ultrices ligula ornare vel. Cras dapibus ipsum eu feugiat ultrices. Morbi sed ipsum sed enim lacinia tempus. Aenean tempus sed purus vel vestibulum.`;
